/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tiyc;

import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class MenuHamming extends javax.swing.JFrame {
    private static String rutaArchivo;
    private static String nombreArchivo;
    private static int numeroHamming;
    private boolean protegido=false;
    /**
     * Creates new form Principal
     * @param ruta este String representa el path del archivo seleccionado
     * por el usuario para realizarle hamming
     * @param nombre este String representa el nombre del archivo seleccionado,
     * se utiliza para mostrarlo por pantalla
     * @param numeroH el número de hamming que determinará cuál Hamming aplicar.
     */
    public MenuHamming(String ruta, String nombre, int numeroH) {
        initComponents();
        rutaArchivo=ruta;
        nombreArchivo=nombre;
        numeroHamming=numeroH;
        this.archivoNombre.setText(nombreArchivo);
        this.numHamming.setText("Hamming "+numeroHamming);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numHamming = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        archivoNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        proteger = new javax.swing.JButton();
        insertar_errores = new javax.swing.JButton();
        corregir_errores = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        desproteger = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 768));
        setSize(new java.awt.Dimension(1350, 768));
        getContentPane().setLayout(null);

        numHamming.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        numHamming.setForeground(new java.awt.Color(240, 240, 240));
        numHamming.setText("Hamming");
        getContentPane().add(numHamming);
        numHamming.setBounds(40, 40, 580, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Archivo seleccionado:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 190, 20);

        volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver);
        volver.setBounds(40, 650, 190, 50);

        archivoNombre.setEditable(false);
        archivoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(archivoNombre);
        archivoNombre.setBounds(40, 150, 230, 30);

        jPanel2.setBackground(new java.awt.Color(27, 104, 134));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 3));

        proteger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        proteger.setText("Proteger archivo");
        proteger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protegerActionPerformed(evt);
            }
        });

        insertar_errores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insertar_errores.setText("Introducir errores");
        insertar_errores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertar_erroresActionPerformed(evt);
            }
        });

        corregir_errores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        corregir_errores.setText("Corregir errores");
        corregir_errores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corregir_erroresActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Hamming");

        desproteger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        desproteger.setText("Desproteger archivo");
        desproteger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desprotegerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(insertar_errores, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proteger, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desproteger, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corregir_errores, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addComponent(proteger, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(desproteger, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(insertar_errores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(corregir_errores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(510, 210, 350, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hex-abstract-material-design-ad.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-130, 0, 2090, 2000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void protegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protegerActionPerformed
        /*leer_archivo_txt(&texto_original,"original.txt");
        generar_Hamming_32(&texto_original,&hamming_32);
        guardar_archivo_txt(&hamming_32,"hamming32.txt");
        ????
        guardar_archivo_txt(generar_Hamming_32(leer_archivo_txt("original.txt")),"hamming32.txt");
        */
        switch(numeroHamming){
            case 8:{
            
            break;}
            
            case 32:{
            
            break;}
            
            case 1024:{
            
            break;}
            
            case 32768:{
            
            break;}
        }
        JOptionPane.showMessageDialog(null, "El archivo fue protegido con éxito.\n Puedes visualizarlo con el nombre 'hamming"+numeroHamming+".txt' en el mismo directorio que el archivo original.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        protegido=true;
        
        
    }//GEN-LAST:event_protegerActionPerformed

    private void insertar_erroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertar_erroresActionPerformed
        
        if (!protegido){
           JOptionPane.showMessageDialog(null, "Debe proteger el archivo primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
        else{
            
            switch(numeroHamming){
                case 8:{

                break;}

                case 32:{

                break;}

                case 1024:{

                break;}

                case 32768:{

                break;}
            }//cierre switch
        JOptionPane.showMessageDialog(null, "Los errores fueron insertados con éxito.\n Puedes visualizarlo con el nombre 'decodificado_con_errores"+numeroHamming+".txt' en el mismo directorio que el archivo original.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }//cierre else
        
        
        
    }//GEN-LAST:event_insertar_erroresActionPerformed

    private void archivoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivoNombreActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.setVisible(false);
        new Principal(rutaArchivo,nombreArchivo).setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void corregir_erroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corregir_erroresActionPerformed

        if (!protegido){
            JOptionPane.showMessageDialog(null, "Debe proteger el archivo primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else{

            switch(numeroHamming){
                case 8:{

                    break;}

                case 32:{

                    break;}

                case 1024:{

                    break;}

                case 32768:{

                    break;}
            }//cierre switch
            JOptionPane.showMessageDialog(null, "El archivo fue desprotegido con éxito.\n Puedes visualizarlo con el nombre 'decodificado_sin_errores"+numeroHamming+".txt' en el mismo directorio que el archivo original.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }//cierre else

    }//GEN-LAST:event_corregir_erroresActionPerformed

    private void desprotegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desprotegerActionPerformed
        if (!protegido){
            JOptionPane.showMessageDialog(null, "Debe proteger el archivo primero", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else{

            switch(numeroHamming){
                case 8:{

                    break;}

                case 32:{

                    break;}

                case 1024:{

                    break;}

                case 32768:{

                    break;}
            }//cierre switch
            JOptionPane.showMessageDialog(null, "El archivo fue desprotegido con éxito.\n Puedes visualizarlo con el nombre 'decodificado"+numeroHamming+".txt' en el mismo directorio que el archivo original.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }//cierre else
    }//GEN-LAST:event_desprotegerActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuHamming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuHamming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuHamming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuHamming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuHamming(rutaArchivo, nombreArchivo, numeroHamming).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField archivoNombre;
    private javax.swing.JButton corregir_errores;
    private javax.swing.JButton desproteger;
    private javax.swing.JButton insertar_errores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel numHamming;
    private javax.swing.JButton proteger;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
