/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tiyc;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Principal extends javax.swing.JFrame {
    String rutaArchivo;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seleccionar = new javax.swing.JButton();
        nombreArchivo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        proteger = new javax.swing.JButton();
        insertar_errores = new javax.swing.JButton();
        desproteger = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        compactar = new javax.swing.JButton();
        descompactar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1350, 768));
        setMinimumSize(new java.awt.Dimension(1350, 768));
        setPreferredSize(new java.awt.Dimension(1350, 768));
        setSize(new java.awt.Dimension(1350, 768));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Bienvenido");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 40, 290, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Archivo seleccionado:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 160, 190, 19);

        seleccionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seleccionar.setText("Seleccionar");
        seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarMouseClicked(evt);
            }
        });
        getContentPane().add(seleccionar);
        seleccionar.setBounds(810, 190, 120, 30);

        nombreArchivo.setEditable(false);
        nombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(nombreArchivo);
        nombreArchivo.setBounds(380, 190, 420, 30);

        jPanel2.setBackground(new java.awt.Color(27, 104, 134));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 3));

        proteger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        proteger.setText("Proteger archivo");
        proteger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protegerActionPerformed(evt);
            }
        });

        insertar_errores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insertar_errores.setText("Introducir errores");
        insertar_errores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertar_erroresActionPerformed(evt);
            }
        });

        desproteger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        desproteger.setText("Desproteger archivo");
        desproteger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desprotegerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Hamming");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertar_errores, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desproteger, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteger, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addComponent(proteger, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(insertar_errores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(desproteger, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(720, 250, 350, 410);

        jPanel1.setBackground(new java.awt.Color(27, 104, 134));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 3));

        compactar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        compactar.setText("Compactar archivo");
        compactar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compactarMouseClicked(evt);
            }
        });
        compactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compactarActionPerformed(evt);
            }
        });

        descompactar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descompactar.setText("Descompactar archivo");
        descompactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descompactarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Huffman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descompactar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compactar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(88, 88, 88)
                .addComponent(compactar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(descompactar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 250, 320, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hex-abstract-material-design-ad.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-130, 0, 2090, 2000);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ejecutar(int opcion, String tipo){ ///Dom(tipo)={huffman, hamming} ///LINUX
                                                   ///Dom(tipo)={huffman.exe, hamming.exe} ///WINDOWS
        Runtime app= Runtime.getRuntime();
        try{
            //app.exec("./"+tipo+" "+this.rutaArchivo+" "+opcion); ///LINUX
            app.exec(tipo+" "+this.rutaArchivo+" "+opcion); ///WINDOWS
        }catch(Exception e){
            System.out.println("Error " + e);
        }
    }
    private void compactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compactarActionPerformed
        // TODO add your handling code here:
        if (nombreArchivo.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //FUNCION EN C CON EL PATH ALMACENADO EN rutaArchivo
        }
    }//GEN-LAST:event_compactarActionPerformed

    private void descompactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descompactarActionPerformed
        // TODO add your handling code here:
        if (nombreArchivo.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //FUNCION EN C CON EL PATH ALMACENADO EN rutaArchivo
            ///this.ejecutar(2, "huffman"); ///LINUX
            this.ejecutar(2, "huffman.exe"); ///WINDOWS
        }
    }//GEN-LAST:event_descompactarActionPerformed

    private void desprotegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desprotegerActionPerformed
        // TODO add your handling code here:
        if (nombreArchivo.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //FUNCION EN C CON EL PATH ALMACENADO EN rutaArchivo
        }
    }//GEN-LAST:event_desprotegerActionPerformed

    private void protegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protegerActionPerformed
        // TODO add your handling code here:
        if (nombreArchivo.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //FUNCION EN C CON EL PATH ALMACENADO EN rutaArchivo
        }
    }//GEN-LAST:event_protegerActionPerformed

    private void insertar_erroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertar_erroresActionPerformed
        // TODO add your handling code here:
        if (nombreArchivo.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //FUNCION EN C CON EL PATH ALMACENADO EN rutaArchivo
        }
    }//GEN-LAST:event_insertar_erroresActionPerformed

    private void compactarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compactarMouseClicked
        // TODO add your handling code here:
        if (nombreArchivo.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //FUNCION EN C CON EL PATH ALMACENADO EN rutaArchivo
            ///this.ejecutar(1, "huffman");///LINUX
            this.ejecutar(1, "huffman.exe");///WINDOWS
        }
        
    }//GEN-LAST:event_compactarMouseClicked

    private void seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarMouseClicked
        // TODO add your handling code here:
        JFileChooser selector=new JFileChooser();
        selector.showOpenDialog(null);
        File f= selector.getSelectedFile();
        if (f!=null){
            rutaArchivo=f.getAbsolutePath();
            String nombreAr=f.getName();
            nombreArchivo.setText(nombreAr);
        }
        
        
    }//GEN-LAST:event_seleccionarMouseClicked

    private void nombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreArchivoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compactar;
    private javax.swing.JButton descompactar;
    private javax.swing.JButton desproteger;
    private javax.swing.JButton insertar_errores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreArchivo;
    private javax.swing.JButton proteger;
    private javax.swing.JButton seleccionar;
    // End of variables declaration//GEN-END:variables
}
